### ISSUE TITLE
Pagebreak 0.6.0 failing to install

### ISSUE THREAD

**Issue by tanakamawere** [CloudCannon/pagebreak#35]
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing jekyll-pagebreak:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-pagebreak-0.6.0/ext
C:/Ruby31-x64/bin/ruby.exe -I C:/Ruby31-x64/lib/ruby/3.1.0 extconf.rb
Installing Pagebreak
Unsupported platform: x64-mingw-ucrt
Please open an issue at https://github.com/CloudCannon/pagebreak/issues

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-pagebreak-0.6.0 for inspection.
Results logged to C:/Ruby31-x64/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/jekyll-pagebreak-0.6.0/gem_make.out

**Comment by bglw** [comment]
Hi @tanakamawere 👋 

The latest Pagefind release changes the distribution method to be a standalone command rather than a Jekyll plugin. See the new [Usage documentation here](https://github.com/CloudCannon/pagebreak/#usage).

I'll close this issue out since there is no longer a gem involved in the process. Let me know if you have any issues with the new installation.
